import "./globals.css"; // Import your global CSS file
import Navbar from "@/components/Menu/Navbar";

export const metadata = {
  icon: "favicon.ico",
  title: "NikkahDeen - Blog template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`noto-bengali dark:bg-dark dark:text-white`}>
        <Navbar />

        <div className="container mx-auto px-5"> {children}</div>
        <p className="text-4xl text-red-500">this is footer</p>
      </body>
    </html>
  );
}
