import Footer from "@/components/Footer/Footer";
import "./globals.css"; // Import your global CSS file
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  icon: "favicon.ico",
  title: "NikkahDeen - Blog template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`noto-bengali dark:bg-dark dark:text-white`}>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
